#!/usr/bin/perl

$uname = qx(uname);
chomp($uname);

$hostname = qx(hostname);
chomp($hostname);

if ( $ENV{'OS'} eq "Windows_NT" )      {
       if ( $ENV{'COMPUTERNAME'} eq "LAFAMIGLIA" ) {
               #chdir "D:\\Sorgenti\\Perl";
       } else {
               print " Not on LaFamiglia. Exiting.\n";
               exit();
       }
} elsif ( $uname eq "Linux" ) {

	#print "Linux\n";

	 if ( $hostname eq "PESTODURO" ) {
		#print "Pestoduro\n";
    	chdir "/home/waleviolaeivan/Sorgenti/FantaCalcGuiNew/";
    	$revision = qx(git rev-parse HEAD);     
    	chomp($revision);       
		#print "$revision\n";
    	system("git add src/revision.h");
    	system("sed 's/XXX/$revision/g' src/revision.h.in > src/revision.h");
	 } else {
    	print " Not on Pestoduro. Exiting.\n";
    	exit(); 
	 }
} else {
		print " System not recognized. Exiting.\n";
		exit();
}

